name: PastelLib
version: '${version}'
main: io.github.yoonseo.pastellib.PastelLib
api-version: '1.21'
commands:
  sit:
    description: Sit on the floor.
  gun:
    description: Hold a gun.
  task:
    description: Assign a task to a character.
  model:
    description: register custom model or load it. ( model [load/register] [modelName] )